# -*- coding: utf-8 -*-
"""LinkedList.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K9Gsn1A1mHRlbq7wXkCDsL0skRi8Ry1P
"""

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Linked():
  List=input().split()
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Linked()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Reverse():
  Arr=input().split()
  head=Node(Arr[0])
  temp=head
  for i in Arr[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  prev=None
  curr=head
  while curr:
    next_node=curr.next
    curr.next=prev
    prev=curr
    curr=next_node
  while prev:
    print(prev.data)
    prev=prev.next
Reverse()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Middle():
  Arr=input().split()
  head=Node(Arr[0])
  temp=head
  count=1
  for i in Arr[1:]:
    new=Node(i)
    temp.next=new
    temp=new
    count+=1
  print(count)
Middle()
'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Size():
    Arr=input().split()
    head=Node(Arr[0])
    temp=head
    for i in Arr[1:]:
      new=Node(i)
      temp.next=new
      temp=new
    temp=head
    print(count(temp))
def count(temp):
    if temp.next==None:
      return 1
    else:
      return 1+count(temp.next)
Size()
'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Search():
  Arr=[int(x) for x in input().split()]
  target=int(input())
  head=Node(Arr[0])
  temp=head
  for i in Arr[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp:
    if temp.data==target:
      print("present")
    temp=temp.next
Search()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Front():
  Arr=[int(x) for x in input().split()]
  New=int(input())
  head=Node(Arr[0])
  temp=head
  for i in Arr[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  head=Node(New)
  head.next=temp
  i=head
  while i:
    print(i.data)
    i=i.next
Front()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Back():
  Arr=[int(x) for x in input().split()]
  New=int(input())
  head=Node(Arr[0])
  temp=head
  for i in Arr[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp.next=Node(New)
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Back()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Mid():
  Arr=[int(x) for x in input().split()]
  New=int(input())
  Target=int(input())
  head=Node(Arr[0])
  temp=head
  for i in Arr[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp:
    if head.data==Target:
      new=Node(New)
      new.next=temp
      head=new
    else:
      if temp.data==Target:
        new=Node(New)
        new.next=temp
    temp=temp.next
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Mid()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Length():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  count=0
  while temp:
    temp=temp.next
    count+=1
  print(count)
Length()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Print():
  List=list(map(int,input().split()))
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp:
    print(temp.data, end=' ')
    temp=temp.next
Print()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Search():
  List=[int(x) for x in input().split()]
  target=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp:
    if temp.data==target:
      print("present")
      return
    else:
      print("False")
    return
    temp=temp.next
Search()
'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def After():
  List=[int(x) for x in input().split()]
  New=int(input())
  Target=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  curr=head
  while curr:
    if curr.data==Target:
      new=Node(New)
      new.next=curr.next
      curr.next=new
    curr=curr.next
  temp=head
  while temp:
    print(temp.data, end=" ")
    temp=temp.next
After()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Before():
  List=[int(x) for x in input().split()]
  New=int(input())
  Target=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp:
    if temp.next.data==Target:
      new=Node(New)
      new.next=temp.next
      temp.next=new
      break
    temp=temp.next
  temp=head
  while temp:
    print(temp.data, end=" ")
    temp=temp.next
Before()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Reverse():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  prev=None
  curr=head
  Next=None
  while curr:
    Next=curr.next
    curr.next=prev
    prev=curr
    curr=Next
    if Next==None:
      head=prev
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Reverse()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Middle():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  count=0
  while temp:
    temp=temp.next
    count+=1
  step=count//2
  temp=head
  while step!=0:
    temp=temp.next
    step-=1
  print(temp.data)
Middle()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Join():
  List1=[int(x) for x in input().split()]
  List2=[int(x) for x in input().split()]
  head1=Node(List1[0])
  temp1=head1
  for i in List1[1:]:
    new=Node(i)
    temp1.next=new
    temp1=new
  head2=Node(List2[0])
  temp2=head2
  for i in List2[1:]:
    new=Node(i)
    temp2.next=new
    temp2=new
  temp1=head1
  temp2=head2
  while temp1 and temp2:
    if temp1.data>temp2.data:
      print(temp2.data)
      temp2=temp2.next
    elif temp2.data>temp1.data:
      print(temp1.data)
      temp1=temp1.next
    else:
      print(temp1.data)
      temp1=temp1.next
      temp2=temp2.next
  while temp1:
    print(temp1.data)
    temp1=temp1.next
  while temp2:
    print(temp2.data)
    temp2=temp2.next
Join()'''

'''class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Delete():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    new=Node(i)
    temp.next=new
    temp=new
  temp=head
  while temp.next!=None:
    if temp.next.data==temp.data:
      temp.next=temp.next.next
      temp=temp.next
    else:
      temp=temp.next
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Delete()'''

#Printing Linked Lists
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Print():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Print()

#If the Node is Present or Not
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Present():
  List=[int(x) for x in input().split()]
  target=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  while temp:
    if temp.data==target:
      print("true")
      return
    temp=temp.next
  else:
    print("False")
Present()

#Insertion at Front
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Front():
  List=[int(x) for x in input().split()]
  New=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  head=Node(New)
  head.next=temp
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Front()

#Insertion After a Given Node
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def After():
  List=[int(x) for x in input().split()]
  Target=int(input())
  New=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  while temp:
    if temp.data==Target:
      newN=Node(New)
      newN.next=temp.next
      temp.next=newN
    temp=temp.next
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
After()

#Insertion Before A given Node
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Before():
  List=[int(x) for x in input().split()]
  Target=int(input())
  New=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  if head.data==Target:
    newN=Node(New)
    newN.next=head
    head=newN
  else:
    while temp:
      if temp.next.data==Target:
        newN=Node(New)
        newN.next=temp.next
        temp.next=newN
        break
      temp=temp.next
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
Before()

#Length of Linked List
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def Length():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  count=1
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
    count=count+1
  print(count)
Length()

#Delete from the Front
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def DeleteF():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  head=head.next
  temp=head
  while temp:
    print(temp.data," ")
    temp=temp.next
DeleteF()

#Delete at the Back
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def DeleteB():
  List=[int(x) for x in input().split()]
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  while temp.next.next!=None:
    temp=temp.next
  temp.next=None
  temp=head
  while temp:
    print(temp.data," ")
    temp=temp.next
DeleteB()

#Delete in between
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def DeleteM():
  List=[int(x) for x in input().split()]
  pos=int(input())
  head=Node(List[0])
  count=1
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    count+=1
    temp=temp.next
  temp=head
  if pos==1:
    head=head.next
  else:
    for can in range(2,count):
      if pos==can:
        temp.next=temp.next.next
        break
      temp=temp.next
    else:
      temp.next=None
  temp=head
  while temp:
    print(temp.data)
    temp=temp.next
DeleteM()

#Get the Nth Node
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def GetN():
  List=[int(x) for x in input().split()]
  Num=int(input())
  head=Node(List[0])
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    temp=temp.next
  temp=head
  count=2
  if Num==1:
    print(head.data)
  else:
    while temp:
      temp=temp.next
      if count==Num:
        print(temp.data)
      count+=1
GetN()

#Get Kth Node from Back
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
def GETk():
  List=[int(x) for x in input().split()]
  K=int(input())
  head=Node(List[0])
  count=1
  temp=head
  for i in List[1:]:
    temp.next=Node(i)
    count+=1
    temp=temp.next
  tot=count-K+1
  count=2
  temp=head
  if tot==1:
    print(head.data)
  else:
    while temp:
      temp=temp.next
      if count==tot:
        print(temp.data)
      count+=1
GETk()