# -*- coding: utf-8 -*-
"""Python Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gb-tX2if6Rc6la-UwX98CQ9yl4fiSOo2
"""

class Node:
  def __init__(self,data):
    self.data=data
    self.children=[]
def addChild(parent,child):
  parent.children.append(child)
a=Node("A")
b=Node("B")
c=Node("C")
d=Node("D")
e=Node("E")
f=Node("F")
addChild(a,b)
addChild(a,c)
addChild(a,d)
addChild(b,e)
addChild(b,f)
def printChildren(node):
  print(node.data)
  for child in node.children:
    printChildren(child)
printChildren(a)
def countNodes(node):
  count=1
  for child in node.children:
    count=count+countNodes(child)
  return count
print(countNodes(a))

def countLeafNodes(node):
  if node.children==[]:
    return 1
  count=0
  for child in node.children:
    count=count+countLeafNodes(child)
  return count

print(countLeafNodes(a))
def calculateHeight(node):
  if node.children==[]:
    return 1
  maxlength=0
  for child in node.children:
    maxlength=max(maxlength,calculateHeight(child))
  return maxlength+1
print(calculateHeight(a))

class Node:
  def __init__(self,data):
    self.data=data
    self.left=None
    self.right=None
A=Node(10)
B=Node(5)
C=Node(2)
D=Node(20)
E=Node(15)
F=Node(30)
A.left=B
A.right=D
B.left=C
D.left=E
D.right=F

def PreOrder(node):
  if node==None:
    return
  print(node.data)
  PreOrder(node.left)
  PreOrder(node.right)
PreOrder(A)

def InOrder(node):
  if node is None:
    return
  InOrder(node.left)
  print(node.data)
  InOrder(node.right)
InOrder(A)

def PostOrder(node):
  if node is None:
    return
  PostOrder(node.left)
  PostOrder(node.right)
  print(node.data)
PostOrder(A)

from collections import deque
class Node:
  def __init__(self,data):
    self.data=data
    self.right=None
    self.left=None
def LevelOrder(node):
  if node is None:
    return
  q=deque()
  q.append(node)
  while q:
    node=q.popleft()
    print(node.data)
    if node.left:
      q.append(node.left)
    if node.right:
      q.append(node.right)
LevelOrder(A)

class Node:
  def __init__(self,data):
    self.data=data
    self.right=None
    self.left=None
def Height(node):
  if node is None:
    return -1
  Left=Height(node.left)
  Right=Height(node.right)
  return max(Left,Right)+1
print(Height(A))

class Node:
  def __init__(self,data):
    self.data=data
    self.right=None
    self.left=None
def Mirror(node):
  if node is None:
    return
  node.left,node.right=node.right,node.left
  Mirror(node.left)
  Mirror(node.right)

class Node:
  def __init__(self,data):
    self.data=data
    self.left=None
    self.right=None
def Height(node):
  if node is None:
    return -1
  Left=Height(node.left)
  Right=Height(node.right)
  return max(Left,Right)+1
def Diameter(node):
  if node is None:
    return 0
  dia=Height(node.left)+Height(node.right)+2
  maxdia=max(dia,Diameter(node.left),Diameter(node.right))
  return maxdia

def Height(node):
  if node is None:
    return -1
  Left=Height(node.left)
  Right=Height(node.right)
  if Left==-2 and Right==-2:
    return False
  if abs(Left-Right)>1:
    return False
  return max(Left,Right)+1
def Balanced(node):
  return Height(node)!=-2

def Search(node,target):
  if node is None:
    return False
  if node.data==target:
    return True
  if target<node.data:
    return Search(node.left,target)
  elif target>node.data:
    return Search(node.right,target)

def Insert(node,data):
  if node is None:
    return Node(data)
  if data<node.data:
    node.left=Insert(node.left,data)
  elif data>node.data:
    node.right=Insert(node.right,data)
  return node

def Delete(node,data):
  if node is None:
    return None
  if node.data==data:
    if node.left is None and node.right is None:
      return None
    if node.left is None:
      return node.right
    if node.right is None:
      return node.left
    if node.right and node.left:
      minvalue=Min(node.right)
      node.data=minvalue.data
      node.right=Delete(node.right,minvalue.data)
  if data<node.data:
    node.left=Delete(node.left,data)
  elif data>node.data:
    node.right=Delete(node.right,data)
  return node
def Min(node):
  while node.left:
    node=node.left
  return node

def Same(root,subRoot):
  if root is None and subRoot is None:
    return True
  elif subRoot is None or root is None:
    return False
  if root.data!=subRoot.data:
    return False
  if root.data==subRoot.data:
    return Same(root.left,subRoot.left) and Same(root.right,subRoot.right)

def isSubtree(root,subRoot):
  if root is None and subRoot is None:
    return True
  elif subRoot is None or root is None:
    return False
  if Same(root,subRoot):
    return True
  return isSubtree(root.left,subRoot) or isSubtree(root.right,subRoot)

def isSubtree(root,queries):
  if root is None:
    return -1
  if Same(root,queries):
    return root.data
  return isSubtree(root.left,queries) or isSubtree(root.right,queries)
def Same(root,queries):
  if root is None:
    return False
  if root.data!=queries:
    return False
  return Same(root.left,queries) and Same(root.right,queries)
def Delete(root):
  if root is None:
    return
  if root.data==queries:
    if root.left is None and root.right is None:
      return None
    if root.left is None:
      return root.right
    if root.right is None:
      return root.left
    if root.left and root.right:
      minvalue=Min(root.right)
      root.data=minvalue.data
      root.right=Delete(root.right,minvalue.data)
    if data<root.data:
      root.left=Delete(root.left,data)
    elif data>root.data:
      root.right=Delete(root.right,data)
    return root
    def Min(root):
      while root.left:
        root=root.left
      return root
def Height(root):
  if root is None:
     return -1
  Left=Height(root.left)
  Right=Height(root.right)
  return max(Left,Right)+1
def treeQueries(root,queries):
  node=isSubtree(root,queries)
  node=Delete(node)
  return Height(root)